### PR TITLE
Fix setting locale failed issue

### PR DESCRIPTION
**Pull request by zalyoung**
I‘ve open a issue https://github.com/gocd/docker-gocd-agent/issues/88

This pull request will set the locale for the go-agent image, 

```
root@3519fd2a5386:/# locale
LANG=en_US.utf8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

Then the gradle problem `Malformed input or input contains unmappable characters` will be solved.

### CODE REVIEW

**Comment by ghost** [comment]
[CLA assistant check](https://cla.gocd.org/gocd/docker-gocd-agent-debian-8?pullRequest=2) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.gocd.org/gocd/docker-gocd-agent-debian-8?pullRequest=2) before we can accept your contribution.<br/><hr/>**zhangy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.gocd.org/check/gocd/docker-gocd-agent-debian-8?pullRequest=2) it.</sub>

**Comment by arvindsv** [comment]
Looks alright to me. Maybe @GaneshSPatil has other opinions?

CLA needs to be signed.

**Review by GaneshSPatil — APPROVED** [review]
LGTM

**Comment by ketan** [comment]
Because the docker file is auto generated, the PR needs to be submitted to the repository at https://github.com/gocd/docker-gocd-agent

**Comment by zalyoung** [comment]
OK, I will submit to https://github.com/gocd/docker-gocd-agent.

Thank you

**Comment by ketan** [comment]
Closing. This was merged on the main repo

**Pull request closed without merging**
